### ISSUE TITLE
Include 3.11.10 in integration tests

### ISSUE THREAD

**Issue by jdonenine** [datastax/adelphi#157]
# Feature Request
### Description
The integration test suite for the adelphi tooling includes the following C* versions: ["2.1.22", "2.2.19", "3.0.23", "3.11.9", "4.0-rc1"]

We should also include the latest 3.11 release: 3.11.10.

### Describe the solution you'd like

3.11.10 be added to the C* testing list - potentially replacing 3.11.9 as the latest 3.11 release.

### Describe alternatives you've considered
N/A

### Additional context
N/A

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/AD-7) by [Unito](https://www.unito.io)
┆Issue Number: AD-7

**Comment by absurdfarce** [comment]
This is being addressed as part of https://github.com/datastax/adelphi/issues/115... see https://github.com/datastax/adelphi/pull/152/commits/98fa005cef22aa752596672a21af6f4622e7b486
