### ISSUE TITLE
Create CircleCI config file

### ISSUE THREAD

**Issue by grighetto** [datastax/adelphi#2]
We have to create a config.yml for cassandra-quality to make it run on CircleCI.
The config file should have steps to install and start the necessary system dependencies (k3d and helm) before launching the Argo workflow.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/AD-74) by [Unito](https://www.unito.io)
┆Issue Number: AD-74

**Comment by absurdfarce** [comment]
Is this ticket still a going concern?

**Comment by grighetto** [comment]
Yes, this was supposed to be the CI/CD work for Adelphi (the workflow/k8s portion).
We have #58 now but that's supposed to cover only the Python package.

**Comment by grighetto** [comment]
Superseded by #166
