### ISSUE TITLE
Improve the schema configuration and documentation

### ISSUE THREAD

**Issue by aboudreault** [datastax/adelphi#21]
We should make it clear in the configuration (values) and documentation (readme) what is supported for each test loaders (nosqlbench and gemini).

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/AD-76) by [Unito](https://www.unito.io)
┆Issue Number: AD-76

**Comment by jdonenine** [comment]
Closing this issue as it's now consumed by newer issues related to the same topics.
