### ISSUE TITLE
Enable a repository of anonymized schemas

### ISSUE THREAD

**Issue by grighetto** [datastax/adelphi#26]
This task is two-fold:

* Create a folder/repository where people can contribute their anonymized schemas (through PRs).
* Add a Helm config to let people choose which schema they want to use when running Adelphi.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/AD-78) by [Unito](https://www.unito.io)
┆Issue Number: AD-78

**Comment by absurdfarce** [comment]
Should we perhaps move the second part of this (select a schema when running Adelphi) to https://github.com/datastax/adelphi/issues/53?  Thoughts @grighetto ?

**Comment by grighetto** [comment]
@absurdfarce yeah, sounds good, since we agreed to separate the "contribution" effort from the "processing" effort, I think it makes sense.

**Comment by absurdfarce** [comment]
Schema has now been created at https://github.com/datastax/adelphi-schemas and made public
