### ISSUE TITLE
Convert a given anonymized schema file to Gemini JSON

### ISSUE THREAD

**Issue by grighetto** [datastax/adelphi#27]
Per #14, we can output a JSON schema to use with Gemini directly from the anonymizer script while connected to a running cluster.
But we also must be able to convert from an existing schema file that has been pre-generated.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/AD-79) by [Unito](https://www.unito.io)
┆Issue Number: AD-79

**Comment by absurdfarce** [comment]
To clarify a bit: the goal here is to incorporate the automated generation of Gemini schema added in https://github.com/datastax/adelphi/pull/22 into the Helm workflow.  This will likely involve something like the following:

* Creation + storage of Gemini schema when clusters are created
* Passing Gemini schema into the invocation of the Gemini app later in the workflow

**Comment by grighetto** [comment]
Resolving issue.

Opened a follow-up bug ticket relate to this: #43
