### ISSUE TITLE
Validate schema-anonymizer on nested UDTs

### ISSUE THREAD

**Issue by grighetto** [datastax/adelphi#3]
The current script works well with the sample schemas we have, but we should validate it against more complex definitions containing UDTs, UDFs.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/AD-82) by [Unito](https://www.unito.io)
┆Issue Number: AD-82

**Comment by josh-mckenzie** [comment]
fwiw, we definitely have the option of just having it Not Work on certain things (bailing out gracefully w/a message on where to submit a gh issue w/request for features, i.e. here) and incrementally adding them over time.

If we assume the large majority of users aren't running complex UDT's and UDF's, then that allows us to get this in front of users sooner and refine over time.

**Comment by grighetto** [comment]
Opened PR #54 that adds:

- Unit tests to cover keyspaces, tables, column types, indexes and complex UDTs;
- Integration tests that run the anonymizer against C* in Docker covering these versions: 2.1.22 / 2.2.19 / 3.0.23 / 3.11.9 / 4.0-beta3;
- A manually-crafted base CQL schema that is compatible across all these versions;
- Comparison of the integration test output with the expected anonymized schema for each version;
- Added proper support for complex UDTs.

Considering the increased scope and the actual work performed here, I'll update the complexity label accordingly.
