### ISSUE TITLE
Schedule Smoke Testing Integration

### ISSUE THREAD

**Issue by grighetto** [datastax/adelphi#38]
The goal of this issue is to include some smoke tests that verify the basic Adelphi features.
We want to catch things like incompatibilities of running  Adelphi or the Cass-Operator on the latest version of k3d.

We can also leverage this work to produce a routine/scheduled cadence of tests against C* trunk to externally verify its continued reliability over time.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/AD-88) by [Unito](https://www.unito.io)
┆Issue Number: AD-88

**Comment by jdonenine** [comment]
Which direction should we go:
* GKE hosted resources (simpler but more costly)
* GH Actions (cheaper but more complicated and perhaps not even possible)
