### ISSUE TITLE
Allow for uploading schemas straight from the anonymizer into the repository

### ISSUE THREAD

**Issue by grighetto** [datastax/adelphi#40]
While discussing a few ideas with @absurdfarce, he suggested that we allow uploading schemas straight from the anonymizer to make the process even more straightforward.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/AD-91) by [Unito](https://www.unito.io)
┆Issue Number: AD-91

**Comment by josh-mckenzie** [comment]
So is the thinking is we have an external repository that users have write-only access w/a submission API w/a token or some kind of UID they can use to then later upsert it? Probably need to lean on token after initial upload required to also get the "auth, don't overwrite" side of it covered... Hm.

Way better UX than "submit a PR" though, I must say.

**Comment by absurdfarce** [comment]
The Github auth stuff has always seemed opaque to me, but as best I can tell the personal access token is bound to a specific user.  We only want to grant access to public repos for a single repo (our schema upload repo) but it looks like use of a personal access token grants access to _every_ repo (this should probably be confirmed).  So we'll want to constrain this in some way.

I _think_ we can create a new user which only has access to the schema upload repo and create the personal access token for that user... that should adequately constrain things.  We _may_ even be able to make the personal access token more public in that case... but I want to do some more testing to confirm that nefarious actors can't do bad things in that case.

I've also confirmed that the personal access token scheme + https://github.com/PyGithub/PyGithub at least supports feature branch creation + content upload.  It looks like PR creation follows on nicely from there... again, more testing required to say for sure.
