### ISSUE TITLE
Publish Python package in PyPI

### ISSUE THREAD

**Issue by grighetto** [datastax/adelphi#48]
We need to create a `setup.py` file for the anonymizer and distribute it as a package in pypi.org.
For some inspiration, we can follow the Python driver example: https://github.com/datastax/python-driver/blob/master/setup.py#L416

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1198513180644180/1198830660243597) by [Unito](https://www.unito.io/learn-more)

**Comment by absurdfarce** [comment]
Note that this work will likely be folded into #40

**Comment by grighetto** [comment]
@absurdfarce and I started this effort in different branches and ended up converging in what's currently in master.
Repurposing this issue to the actual publishing of the package in PyPI.

**Comment by absurdfarce** [comment]
This wound up not being completely covered by #40 so we'll be pursuing it as it's own effort

**Comment by absurdfarce** [comment]
@grighetto + @jdonenine ... do we agree there's nothing left to do for this issue now that the package is live?

**Comment by jdonenine** [comment]
Yup, I actually thought I had closed it, apparently, I only moved it in the project... fail 😞 

![image](https://user-images.githubusercontent.com/7901615/102932950-4be09480-446f-11eb-8c03-c398f362fd31.png)

Close away!

**Comment by absurdfarce** [comment]
:ohyeah:
