### ISSUE TITLE
Schema metadata should be friendly to automated parsing

### ISSUE THREAD

**Issue by absurdfarce** [datastax/adelphi#74]
Current format for metadata stored in schemas contributed by the "adelphi" tool is a homegrown format designed for ease of reading... but it isn't super-easy to parse in an automated fashion:

```
//Schema metadata:
//@created_at = 2020-12-10T09:52:39.793838
//@github_user = absurdfarce
//@hashed_ks_name = 9oeoJFuUPUpGOIjokdIIuwsJcmGny03H8MyjkovpV4w=
//@dc-count = 1
//@host-count = 1
```

This should be converted to something more friendly to programmatic parsing

**Comment by absurdfarce** [comment]
Another option here would be to decouple schema and metadata.  Create a separate metadata file using some well-known name or in some well-known location containing metadata for each schema.  The schema file can then be pure content and the metadata file could be something very parse-friendly: JSON, TOML, whatever.

Think how Maven or Gradle structure their package repositories, something like that

**Comment by jdonenine** [comment]
That approach would definitely solve the formating question.  We could go with some straightforward like json or yaml in a plain file.  I'd think the challenge might be how to preserve the linkage between the two files.

Maybe create a directory for each schema and put the two side by side, the metadata could contain a reference to the schema file path perhaps?

user -> 
  hashedschemaid -> 
    hashedschemaid
    hashedschemaid.metadata.json

Something like that? What are you thinking?

**Comment by absurdfarce** [comment]
I haven't formed a really good opinion yet but I was considering something along the lines of what you're describing @jdonenine .  I was thinking a directory per schema; that directory would contain the raw schema file and the metadata file as discrete files.  The schema file would just be a straight text file (containing CQL/Gemini depending on what was selected for export) while the metadata would be... probably JSON to keep it simple.  We can just use well-known names for the files within the schema directory... something like "schema.txt" and "metadata.json" should work.

The big advantage I see to something like that is it provides a clean avenue for future expansion.  By keeping schema-specific files in their own directory you create isolated spaces where you can do interesting things going forward.  So say at some point you want to track versions of an individual schema over time you could do so; you'd need "schema-timestamp.txt" for a resource name, but you see where I'm going with this.
