### ISSUE TITLE
Improve user documentation

### ISSUE THREAD

**Issue by jdonenine** [datastax/adelphi#83]
Update documentation (via READMEs for now) to reflect guidance and details needed for a user to use Adelphi for an end-to-end workflow, with a focus on integrity testing.

Provide quick start type guidance, architectural design details, and any other relevant details.

It should be enough that a new user can find Adelphi, grab onto it, and start using it with minimal friction.

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/AD-55) by [Unito](https://www.unito.io)
┆Issue Number: AD-55

**Comment by grighetto** [comment]
Resolved in #97
