### ISSUE TITLE
Support export/output of test run results for CI/CD integration

### ISSUE THREAD

**Issue by jdonenine** [datastax/adelphi#85]
# Feature Request
### Description
Details are TBD

### Additional context

┆Issue is synchronized with this [Jira Task](https://datastax-oss.atlassian.net/browse/AD-54) by [Unito](https://www.unito.io)
┆Issue Number: AD-54

**Comment by grighetto** [comment]
By means of #64 we now have what we need to expose the results to a CI pipeline.
The result files will be exposed through a webserver that job the runner (Jenkins, CircleCI, ...) can hit and download the data from and then move it to the appropriate storage service for archival.

That's a generic approach that should work with most scenarios. Until we have more specific needs, we shouldn't have to add more complexity.
